[package]
name = "flowshot-capture-wayland"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/flowoss/flowshot"
authors = ["FlowShot Contributors"]

[lib]
crate-type = ["rlib"]

[dependencies]
flowshot-core = { path = "../flowshot-core" }
flowshot-capture = { path = "../flowshot-capture" }
wayland-client = { workspace = true }
wayland-protocols = { workspace = true }
calloop = { workspace = true }
calloop-wayland-source = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
nix = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
image = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
