[package]
name = "flowshot-capture"
version = "0.1.0"
edition = "2024"
license.workspace = true
repository = "https://github.com/flowoss/flowshot"
authors = ["FlowShot Contributors"]

[lib]
crate-type = ["rlib"]

[dependencies]
flowshot-core = { path = "../flowshot-core" }
async-trait = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
bytes = { workspace = true }
image = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
