[package]
name = "flowshot-core"
version = "0.1.0"
edition = "2024"
license.workspace = true
repository = "https://github.com/flowoss/flowshot"
authors = ["FlowShot Contributors"]

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
image = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[lints]
workspace = true