//! Build-time tray-logo rasterization: `assets/logo.svg` -> the SNI pixmap
//! sizes (`logo_raster::SIZES`), embedded as raw ARGB32 wire bytes.
//!
//! The daemon binary carries ~18 KB of pixmaps instead of the 410 KB PNG
//! export or a runtime SVG stack - resvg stays a build-only dependency
//! (the `flowshot-ui` icon-atlas build.rs is the precedent).

#[path = "src/logo_raster.rs"]
mod logo_raster;

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=../../assets/logo.svg");
    println!("cargo:rerun-if-changed=logo_raster.rs");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir =
        env::var("OUT_DIR").unwrap_or_else(|error| panic!("OUT_DIR must be set: {error}"));
    let svg = fs::read("../../assets/logo.svg")
        .unwrap_or_else(|error| panic!("assets/logo.svg must be readable: {error}"));

    let mut entries = String::new();
    for size in logo_raster::SIZES {
        let blob = Path::new(&out_dir).join(format!("logo_{size}.argb"));
        fs::write(&blob, logo_raster::raster_argb(&svg, size))
            .unwrap_or_else(|error| panic!("{} must be writable: {error}", blob.display()));
        // `writeln!` into a `String` is infallible (`fmt::Write for String`).
        let _ = writeln!(
            entries,
            "    include_bytes!(concat!(env!(\"OUT_DIR\"), \"/logo_{size}.argb\")),"
        );
    }

    let count = logo_raster::SIZES.len();
    let code = format!(
        "// Generated by build.rs from assets/logo.svg - do not edit.\n\
         \n\
         /// Pixmap sizes offered to the host (it picks the closest and scales).\n\
         pub const SIZES: [u32; {count}] = {:?};\n\
         \n\
         /// The idle `FlowShot` logo per [`SIZES`] entry: ARGB32 big-endian\n\
         /// wire bytes (A,R,G,B per pixel, row-major, premultiplied alpha),\n\
         /// `size * size * 4` bytes each.\n\
         pub const LOGO_ARGB: [&[u8]; {count}] = [\n\
         {entries}];\n",
        logo_raster::SIZES,
    );
    fs::write(Path::new(&out_dir).join("logo_icons.rs"), code)
        .unwrap_or_else(|error| panic!("logo_icons.rs must be writable: {error}"));
}
