[package]
name = "flowshot-daemon"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/flowoss/flowshot"
authors = ["FlowShot Contributors"]

[[bin]]
name = "flowshot"
path = "src/main.rs"

[dependencies]
flowshot-core = { path = "../flowshot-core" }
flowshot-capture = { path = "../flowshot-capture" }
flowshot-actions = { path = "../flowshot-actions" }
zbus = { workspace = true }
notify-rust = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true